[project]
name = "chore-granian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.5",
    "granian>=1.6.4",
]

[dependency-groups]
dev = [
    "httpx[cli]>=0.28.0",
]
